Some cleanup

diff --git a/doccomp b/doccomp
--- a/doccomp
+++ b/doccomp
@@ -7,7 +7,8 @@ usage()
 
 file_exists()
 {
-	test ! -f "${file}" && echo "${0##*/}: ${file}: file not found" 1>&2 && exit 1
+	test ! -f "${file}" &&
+	echo "${0##*/}: ${file}: file not found" 1>&2 && exit 1
 }
 
 test ${#} -eq 0 && usage
@@ -26,5 +27,5 @@ case "${ext}" in
 			-V mainfont=Arial \
 			-o "${base}.pdf" ;;
 	tex)	pdflatex ${file}
-		rm -f *.aux *.log *.out *.bcf *.run.xml *.bbl *.blg *-blx.bib ;;
+		rm -f *.log *.out .bcf *.run.xml *.bbl *.blg *-blx.bib ;;
 esac
